### ISSUE TITLE
Tread + Packets

### ISSUE THREAD

**Issue by Bodeyibl** [kimpro12/UdpFlood#1]
afther i put the target IP and port 80. What do i need to put in treads and packes? i just keep booting my self..

**Comment by kimpro12** [comment]
this is l4 ddos don't use port 80 it not ddos l7 (web)

Vào Th 6, 18 thg 3, 2022 vào lúc 01:20 Bodey ***@***.***>
đã viết:

**Comment by Bodeyibl** [comment]
so how do i use it then?
